### PR TITLE
FSRS4RemNote v1

### PR DESCRIPTION
**Pull request by bjsi**
### Changes 🔁

- I just released RemNote plugin SDK v0.0.15 which adds support for plugin schedulers.
- I copied the code from the Anki plugin and tried to convert some of it. I don't fully understand it :sweat_smile: so you will need to finish it off. The only thing you should need to implement is the `getNextSpacingDate`
- Please let me know if you run into any issues! I am happy to help however I can.

#### Registering the Scheduler

```ts
await plugin.scheduler.registerCustomScheduler(
    "FSRS4RemNote",
    Object.values(defaultParameters)
  )
```

- This registers your custom scheduler with RemNote.
- After users install your plugin, they will see a dropdown menu in the Custom Scheduling menu where they can choose to use your scheduler.

image

- Users can customise the scheduling parameters:

image

#### Registering the Schedule Card Callback

```ts
  await plugin.app.registerCallback<SpecialPluginCallback.SRSScheduleCard>(
    SpecialPluginCallback.SRSScheduleCard,
    getNextSpacingDate
  )
```

- So that RemNote can get the next spacing date for a flashcard from your plugin, you need to register the SRSScheduleCard callback.
- The `getNextSpacingDate` function will get called:
  - When the user does a repetition in the queue.
  - Also when calculating the example repetition dates here: image

#### Implementing the getNextSpacingDate function

```ts
  async function getNextSpacingDate(args: {
    history: RepetitionStatus[],
    schedulerParameters: Record<string, unknown>,
  }) {
    const {history, schedulerParameters} = args;
    const lastRep = history[history.length - 1]
    ...
  }
```

- `getNextSpacingDate` gets passed the repetition history and scheduler parameter values.
- You should use them to calculate the `nextDate` in milliseconds and optionally some custom `pluginData` (for your plugin it would be the ease, difficulty, stability etc.)
- `pluginData` is stored on the repetition.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Thanks to your contribution! I will check it tomorrow.

**Comment by L-M-Sherlock** [comment]
I implement the `getNextSpacingDate`. But what is `Early` in the examples?

image

**Comment by L-M-Sherlock** [comment]
And I found that there is not `customData` in `RepetitionStatus`. There is `pluginData` in `RepetitionStatus`.

**Comment by bjsi** [comment]
> And I found that there is not customData in RepetitionStatus. There is pluginData in RepetitionStatus.

Ah this is my mistake, I renamed it to pluginData, but forgot to update the RepetitionStatus, I'll fix this and publish a new SDK version on Monday

> What is early

Early is the score when you click this button I think. Is it calling your plugin when you press that button? I may have made a mistake.

image

**Comment by L-M-Sherlock** [comment]
> Early is the score when you click this button IIRC. It's basically used when you pressed Show Answer too quickly. Is it calling your plugin when you press that button? I may have made a mistake.

If I press `Skip`, it will generate a record and append to `history`. 

```json
{
    "date": 1670053159561,
    "score": 0.01,
    "responseTime": 7973,
    "revealTime": 3750,
    "scheduled": 1670052252782,
    "isCram": false,
    "metadata": {
        "mobile": false,
        "cardsInSession": 9,
        "cardsToday": 9,
        "remainingCards": 1
    },
    "lazyLoad": false,
    "scheduler": 3,
    "pluginData": {
        "difficulty": 6,
        "stability": 1,
        "stage": 2
    }
}
```

However, I need to calculate the real elapsed days since last review by `elapsedDays = (lastRep.date - history[history.length - 2].date) / (1000 * 60 * 60 * 24)`.

**Comment by L-M-Sherlock** [comment]
And I use `history.length` as the condition to distinguish new cards and old cards. But if the user press `Skip` in the first learning, the `history.length` condition will induce some problems.

**Comment by L-M-Sherlock** [comment]
And these settings are unused. How to remove them?

image

**Comment by L-M-Sherlock** [comment]
> Early is the score when you click this button IIRC. It's basically used when you pressed Show Answer too quickly. Is it calling your plugin when you press that button? I may have made a mistake.

I press `Sikp`, then the `pluginData` is wrote into history. It is weird.

image

**Comment by bjsi** [comment]
How about this:

1. `if (lastRep.score === QueueInteractionScore.Skip) return null` in this case RemNote's default scheduler will handle the skip button and pluginData will not get added to the repetition
2. Filter any repetitions where `lastRep.score === QueueInteractionScore.Skip` out of the history array, basically just act as if they didn't exist.

**Comment by bjsi** [comment]
> And these settings are unused. How to remove them?

1) Remove them from the defaultParameters object
2) We save the parameters internally so users can customize them. I will need to add some code to update the internal data when parameters registered by the plugin developer get added or removed. This will be available in the next remnote update

**Comment by L-M-Sherlock** [comment]
> 1. `if (lastRep.score === QueueInteractionScore.Skip) return null` in this case RemNote's default scheduler will handle the skip button and pluginData will not get added to the repetition

image

**Comment by L-M-Sherlock** [comment]
It is ready to release. Could you give it a try?

**Comment by bjsi** [comment]
Excellent work, I will do tests on Monday :+1:

**Comment by bjsi** [comment]
Some of the intervals seem a bit strange to me, eg:

image

- Hard button doubles the interval. Seems like it should either stay the same or decrease.
- Solid button only increases interval to 10 mins

Is this expected behavior?

**Comment by L-M-Sherlock** [comment]
> * Solid button only increases interval to 10 mins

It only happens when the card is new. I implemented the learning steps like the one of Anki.

**Comment by L-M-Sherlock** [comment]
> * Hard button doubles the interval. Seems like it should either stay the same or decrease.

I assume that `Hard` means `Pass` in SuperMemo.

**Comment by L-M-Sherlock** [comment]
I merged this branch. The current fsrs4remnote is 80% similar to fsrs4anki. Some features will be implemented in the future:

1. Fuzz with seed (ensure the fuzz is determined in one review)
2. Export review logs for optimization (is it possible?)

**Pull request merged**
